plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.testng:testng:7.7.0'
    implementation 'io.appium:java-client:8.5.1'
    implementation 'org.seleniumhq.selenium:selenium-java:4.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.opencsv:opencsv:5.9'
    implementation 'org.slf4j:slf4j-simple:2.0.9'
    testImplementation 'io.qameta.allure:allure-testng:2.20.0'
}

test {
    useTestNG()
}
